/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElText: typeof import('element-plus/es')['ElText']
    FluentCheckBox: typeof import('./src/components/fluent-ui/FluentCheckBox.vue')['default']
    FluentInput: typeof import('./src/components/fluent-ui/FluentInput.vue')['default']
    FluentUIButton: typeof import('./src/components/fluent-ui/FluentUIButton.vue')['default']
    FluentUIInput: typeof import('./src/components/fluent-ui/FluentUIInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
